
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGGREGATION ASSOCIATION CLASS COLON COMPOSITION END EXTENSION IDENTIFIER LINE REL START STRING\n    diagram : START relations END\n    diagram : START IDENTIFIER relations END\n    diagram : START STRING relations END\n    \n    relations : relation\n    relations : relation relations\n    \n    relation : IDENTIFIER REL LINE IDENTIFIER\n    \n    relation : IDENTIFIER LINE REL IDENTIFIER\n    '
    
_lr_action_items = {'START':([0,],[2,]),'$end':([1,7,14,17,],[0,-1,-2,-3,]),'IDENTIFIER':([2,4,5,6,15,16,18,19,],[4,8,8,8,18,19,-6,-7,]),'STRING':([2,],[5,]),'END':([3,6,9,12,13,18,19,],[7,-4,14,17,-5,-6,-7,]),'REL':([4,8,11,],[10,10,16,]),'LINE':([4,8,10,],[11,11,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'diagram':([0,],[1,]),'relations':([2,4,5,6,],[3,9,12,13,]),'relation':([2,4,5,6,],[6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> diagram","S'",1,None,None,None),
  ('diagram -> START relations END','diagram',3,'p_diagram','parser.py',11),
  ('diagram -> START IDENTIFIER relations END','diagram',4,'p_diagram','parser.py',12),
  ('diagram -> START STRING relations END','diagram',4,'p_diagram','parser.py',13),
  ('relations -> relation','relations',1,'p_relations','parser.py',45),
  ('relations -> relation relations','relations',2,'p_relations','parser.py',46),
  ('relation -> IDENTIFIER REL LINE IDENTIFIER','relation',4,'p_l_relation','parser.py',57),
  ('relation -> IDENTIFIER LINE REL IDENTIFIER','relation',4,'p_r_relation','parser.py',70),
]
