[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyplaml"
version = "0.0.1"
description = "Package for converting PlantUML diagrams to Manim representation."
requires-python = ">=3.10"
dependencies = ["ply", "manim", "networkx", "pygraphviz"]