@startuml "BasicElements"
class myClass
Class "my Class"
abstract "myAbsClass1"
abstract myAbsClass2
abstract class myAbsClass3
abstract class "my abs class4"
enum myEnum
enum "my Enum"
exception myException
exception "my Exception"
interface myInterface
interface "my Interface"
' metaclass myMetaClass
' metaclass "my Meta Class"
protocol myProtocol
protocol "my Protocol"
' stereotype myStereotype
' stereotype "my Stereotype"
struct myStruct
struct "my Struct"
@enduml