@startuml "Relations"
Class01 "1" -- "25" Class02
Class03 "one" --* Class04
Class05 --o "many" Class06
Class07 .. Class08
Class09 -- Class10
Class11 ..|> Class12
Class13 --> Class14
Class15 ..> Class16
Class17 "1" <|.. "25" Class18
Class19 "one" <|.. Class20
Class21 <|.. "many" Class22
Class23 <--* Class24

class class25 extends class26
class "class25_str" extends "class26_str"
interface intf EXTENDS base_interface
class class27 implements interfacex
abstract class28 implements interfacey
@enduml