@startuml "Class Body"
interface Dummy {
  String data
  {field} Int propertyWithBraces()

  void methods()
  {static} int staticMethod()
  {abstract} String abstractMethod()
  {method} methodWithoutBrackets
  {static} staticAbstractmethodWithoutBrackets {abstract} {method}
}

class Flight {
   flightNumber : Integer
   departureTime : Date
}

Dummy <-- Flight
@enduml
