@startuml "Class attributes"
C1 <|--- "test C2" C2
C1 <|--- C3
C1 "test C4" <|--- C4

C1 : -Int count
C1 : -String name
C1 : +getCount()
C1 : #getName()

C2 : +print()

C3 : #add()
C3 : ~getLength()

C4 "*" *-- "1" C5 : has
C4 "many" *-- "one" C6 : contains

C7 --> C2
C8 "test C8" --> C2

C7 : -float price

C9 --> C5

C9 : show()
@enduml